<link rel="stylesheet" href="/css/signin.css">
<div class="navegacao" style="margin-top: 15px;"><!--Barra de navegação-->
    <div class="container">
    <nav class="navbar navbar-expand-sm">
        <a class="home" href="/home"><button class="btn btn-custom btn-azul home"><i class="fas fa-arrow-left"></i>Home</button></a>
        <ul class="navbar-nav ml-auto">
        <div class="flex-row justify-content-between d-none d-md-flex">
            <div class="flex-row">
            <span class="mr-3">Ainda não tem uma conta?</span>
            <a href="/inscreverse?page=1"><button class="btn btn-custom btn-azul cadastre">Cadastre-se</button></a>
            </div>
        </div>
        </ul>
    </nav>
    </div>
</div><!--Fim Barra de navegação-->
<section class="containerLogin"><!--Container Login-->
    <div class="flex-row justify-content-center">
        <div class="logoRegistro"> <!--Logo-->
        <img src="img/logo2.png" class="image img-fluid mt-2 mr-2">
        </div>
    </div>
    <div class="box loginBox"> 
    <form method='post' action='/autenticar'>
        <h3 class="pb-2" style="padding-top: 30px;">Acesse sua conta.</h3>
        <div class="divider d-flex align-items-center my-4"></div>
        <?php if($this->view->login == 'erro') { ?>
			<div class="row">
				<div class="col">
					<span class="text text-danger">*Email e ou senha inválido(s)</span>
				</div>
			</div>
		<?php } ?>
        <span class="logintext">E-mail ou Usuário:</span>
        <div class="input-group form-group mb-4">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
        </div>
        <input name="email" type="email" class="form-control" placeholder="">
        </div>
        <span class="logintext">Senha:</span>
        <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
            <input name="senha" type="password" class="form-control" placeholder="">
        </div>
        <div class="row mb-4">
        <div class="col-md-6 d-flex justify-content-center">
            <div class="custom-control custom-checkbox custom-control-inline">
            <input id="chk1" type="checkbox" name="chk" class="custom-control-input">
            <label for="chk1" class="custom-control-label text-sm">Lembre me</label>
            </div>
        </div>
        <div class="col-md-6 d-flex justify-content-center">
            <a href="#" style="color: #2a475e;">Esqueceu sua senha?</a>
        </div>
        </div>
        <div class="form-group">
        <input type="submit" value="Entrar" class="btn btn-block btn-custom login_btn mb-3">
        </div>
        <div class="text-center">
        <small class="font-weight-bold"><p>Não tem uma conta? <a style="color: red;" href="/inscreverse?page=1">Registrar</a></p></small>
        </div>
    </form>
    </div><!--Fim Box Login-->
</section><!--Fim Container Login-->
