<link rel="stylesheet" href="/css/home.css">
<div class="panel panel-default">
  <div class="panel-body">
    <?php include "header.php" ?>
    <section id="home" class="d-flex mt-3">
      <div class="container mt-3">
        <div class="row pb-3">
          <div class="col-md-1"></div>
          <div class="col-md-10 capa">
            <div id="carousel-home" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="img-fluid" src="img/pessoas.jpg">
                </div>
                <!--
                <div class="carousel-item">
                  <img class="img-fluid" alt="Toguro" src="https://c.tenor.com/ZRHlOrai4F4AAAAM/toguro-lançando-a-braba-toguro.gif">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>Toguro</h5>
                  </div>
                </div>
                -->
                <div class="carousel-item">
                  <img class="img-fluid" src="img/pessoas2.jpg">
                </div>
                <div class="carousel-item">
                  <img class="img-fluid" src="img/pessoas3.jpg">
                </div>
              </div>
              <a href="#carousel-home" class="carousel-control-prev" data-slide="prev">
                <i class="fas fa-angle-left fa-3x"></i>
              </a>
              <a href="#carousel-home" class="carousel-control-next" data-slide="next">
                <i class="fas fa-angle-right fa-3x"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section><!-- Home -->
    <section class="mb-3 boxHomeStyle">
      <div class="container pt-3">
        <div class="row">
          <div class="col-md-3 ml-auto boxHome">
            <i class="fas fa-coins"></i>
            <h5>Fundos de Investimentos</h5>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum optio similique tenetur qui error vero rerum fuga a! Possimus explicabo nam quidem</p>
            <small><a href="#">Saiba mais</a></small>
          </div>
          <div class="col-md-3 m-auto boxHome">
            <i><img src="img/arrow-trend-up-solid.svg" style="height: 20px"></i>
            <h5>Bolsa de Valores</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem praesentium atque quod. Eligendi hic neque ipsam, in repellendus ad laudantium dolorum quaerat ea provident</p>
            <small><a href="#">Saiba mais</a></small>
          </div>
          <div class="col-md-3 mr-auto boxHome">
            <i class="fas fa-wallet"></i>
            <h5>Renda Fixa</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem praesentium atque quod. Eligendi hic neque ipsam, in repellendus ad laudantium dolorum quaerat ea provident</p>
            <small><a href="#">Saiba mais</a></small>
          </div>       
        </div>            
      </div>
    </section>
    <?php include "footer.php" ?>
  </div>
</div>