<link rel="stylesheet" href="/css/home.css">
<div class="panel panel-default">
  <div class="panel-body">
  <?php include "header.php" ?>
    <section id="notFound404" class="d-flex pb-3 mt-3"><!---->
      <div class="container mt-3">
        <h1 style="text-align: center;">Página não encontrada!</h1>
      </div>
    </section><!--Fim-->
    <div style="margin-bottom: 580px;"></div>
    <?php include "footer.php" ?>
  </div>
</div>